---
environment: development
chdir: <%= app_dir %>
pid: <%= pids_dir %>/thin.pid
rackup: <%= rackup_file %>
log: <%= log_dir %>/thin.log
socket: <%= sockets_dir %>/thin.sock
max_conns: 1024
servers: 1
timeout: 30
max_persistent_conns: 512
daemonize: true
tag: jbs
